### ISSUE TITLE
检测出病毒被系统删除了

### ISSUE THREAD

**Issue by yanpengqing** [Admirepowered/Fix-Pandownload-login#2]
下载完就被系统自动删除了 
没法用啊

**Comment by ykwia** [comment]
我的也被删除了，之前下载还没事

**Comment by frankandtony** [comment]
什么系统?

**Comment by ykwia** [comment]
Windows 10， Chrome 浏览器自动删除




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "frankandtony"<notifications@github.com&gt;; 
发送时间: 2020年6月20日(星期六) 晚上6:12
收件人: "Admirepowered/Fix-Pandownload-login"<Fix-Pandownload-login@noreply.github.com&gt;; 
抄送: "孙畅"<sunxiaoxiao1221@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Admirepowered/Fix-Pandownload-login] 检测出病毒被系统删除了 (#2)





 
什么系统?

**Comment by Womsxd** [comment]
自己加白名单啊，易语言写的不爆毒那就是个奇迹啊！！！

**Comment by Admirepowered** [comment]
脱壳完就报毒，我也不知道为什么，没有再吧UPX加壳回去，不过应该是误报

**Comment by ykwia** [comment]
已经设置好了，感谢分享。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Admirepowered"<notifications@github.com&gt;; 
发送时间: 2020年6月22日(星期一) 晚上10:01
收件人: "Admirepowered/Fix-Pandownload-login"<Fix-Pandownload-login@noreply.github.com&gt;; 
抄送: "孙畅"<sunxiaoxiao1221@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Admirepowered/Fix-Pandownload-login] 检测出病毒被系统删除了 (#2)





 
脱壳完就报毒，我也不知道为什么，没有再吧UPX加壳回去，不过应该是误报

**Comment by pluveto** [comment]
不是病毒的话请开个源，不然真不敢用

**Comment by Admirepowered** [comment]
> 不是病毒的话请开个源，不然真不敢用

你得找Pandownload作者开源啊，带点nz

**Comment by pluveto** [comment]
> > 不是病毒的话请开个源，不然真不敢用
> 
> 你得找Pandownload作者开源啊，带点nz

nz记得放放水，作者发布的没毒，就你有毒
